Repository ComicScrip/p2-test, pull requests merged in 2020-10, with the labels that each got.

#1 i'm a cat
  index.html
Labels: Ready for validation

#3 adds a dog to homepage
  index.html
Labels: WIP

#5 project init
  .gitignore
  README.md
  index.html
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/serviceWorker.js
  src/setupTests.js
  yarn.lock
Labels: Ready for prod
